#include "analyzer.h"
#include <unordered_set>

//Serialize conditions
//Used to compare conditions
string Analyzer::serializeCondition(
    Condition* condition
) {

    //FACT CONDITION
    if (FactCondition* fact = dynamic_cast<FactCondition*>(condition)) {

        return
            "FACT(" + fact->identifier + ")";
    }

    //COMPARISON CONDITION
    if (ComparisonCondition* comp = dynamic_cast<ComparisonCondition*>(condition)) {

        return
            "CMP(" + comp->identifier + comp->op + to_string(comp->value) + ")";
    }

    // AND CONDITION
    if (AndCondition* andCond = dynamic_cast<AndCondition*>(condition)) {
        return "AND(" + serializeCondition(andCond->left) + "," + serializeCondition(andCond->right) + ")";
    }

    return "";
}



// CONFLICT DETECTION
// Same action generated by multiple rules
void Analyzer::detectConflicts(Program* program) {

    unordered_map<string,vector<string>> producers;

    //Group rules by action
    for (Rule* rule : program->rules) {

        producers[rule->action].push_back(rule->name);
    }

    //Print conflicts
    for (auto& pair : producers) {

        if (pair.second.size() > 1) {

            cout << "Action " << pair.first << " generated by ";

            for (size_t i = 0;i < pair.second.size(); i++) {

                cout << pair.second[i];

                if (i + 1 < pair.second.size()) {

                    cout << ", ";
                }
            }

            cout << endl;
        }
    }
}

//REDUNDANT RULES
//Same condition + same action
void Analyzer::detectRedundantRules(Program* program) {

    unordered_map<string,vector<string>> ruleGroups;

    //Build signature
    for (Rule* rule : program->rules) {

        string signature = serializeCondition(rule->condition) + "->" + rule->action;

        ruleGroups[signature].push_back(rule->name);
    }

    //Print redundant groups
    for (auto& pair : ruleGroups) {

        if (pair.second.size() > 1) {

            cout << "Redundant rules: ";

            for (size_t i = 0; i < pair.second.size(); i++) {

                cout << pair.second[i];

                if (i + 1 < pair.second.size()) {

                    cout << ", ";
                }
            }

            cout << endl;
        }
    }
}

// POTENTIALLY INACTIVE RULES
// Simplified approach:
//
// If rule condition is:
// - comparison:
//     considered potentially inactive
// - fact condition:
//     check whether another rule
//     generates that fact

void Analyzer::detectInactiveRules(Program* program) {

    //All generated actions
    unordered_set<string> actions;

    for (Rule* rule : program->rules) {

        actions.insert(rule->action);
    }

    //Analyze conditions
    for (Rule* rule : program->rules) {

        //FACT CONDITION
        if (FactCondition* fact = dynamic_cast<FactCondition* > (rule->condition)) {
            //No rule generates this fact
            if (actions.count(fact->identifier) == 0) {

                cout << "Potentially inactive rule: " << rule->name << endl;
            }
        }

        //COMPARISON CONDITION
        else if (dynamic_cast<ComparisonCondition* >(rule->condition)) {

            cout << "Potentially inactive rule: " << rule->name << endl;
        }
    }
}